# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Publish CPU build to Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: nlp-cpu
        username: neilfern
        password: ${{ secrets.DOCKER_KEY }}
        registry: https://hub.docker.com/repository/docker/neilfern/nlp-cpu
        dockerfile: ./docker/pytorch-cpu/Dockerfile
        #workdir: $GITHUB_WORKSPACE/
        tag_names: ${GITHUB_SHA::8}, latest
        # snapshot: # optional:  
        # buildargs: # optional
        # cache: # optional
        # tag_semver: # optional
